### ISSUE TITLE
Show more than one currency

### ISSUE THREAD

**Issue by sinanboecker** [lainsce/coin#11]
It would be great if you could see more than one currency in one window. Alternatively it would be great to be able to open Coin more than once to see more currencies.

**Comment by lainsce** [comment]
By the way, let's go through this together:

By seeing more of one currency, you mean:
**A.** There's an add button which opens up a new Coin window in the titlebar.
or
**B.** There's an add button which opens up more comboboxes (at least 2 more) for multi-tracking.

Which of those is more like what you expect for this?

**Comment by sinanboecker** [comment]
A very simple mockup of what I was thinking of:
![shot](https://user-images.githubusercontent.com/7779514/28128579-750e64b0-6730-11e7-95ed-86cd76489327.png)
Show a list of Currencies and add a way to add more (and delete exisitng ones)

**Comment by lainsce** [comment]
Hmm, but that would defeat the purpose of the app, which is to be an applet, and do one thing and do it well. 😛

**Comment by sinanboecker** [comment]
I think it would still be pretty simple, it would just show more than one currency. Maybe limit to 3?
But ultimately it's your decision :) An easy alternative would be the possibility to open more than one instance of coin. Then I could open one window for BTC and one for some other currency.

**Comment by lainsce** [comment]
I'm going to add in a button to open a new instance of Coin in the next release.

**Comment by eljefuri** [comment]
For what it's worth, the suggestion that @gorrila made makes more sense to me than the UX complexity of figuring out how to run multiple instances of Coin.

**Comment by lainsce** [comment]
I'll think about how to best show this.
