### ISSUE TITLE
Does not remember window position

### ISSUE THREAD

**Issue by SleepingPanda** [lainsce/coin#12]
Coin does not remember window position on restart.

**Comment by lainsce** [comment]
Will fix, expect a release soon

**Comment by lainsce** [comment]
Okay, after some testing, it does remember position.
Are you on the latest release?

**Comment by SleepingPanda** [comment]
Yes. On restarting eOS Loki, and relaunching coin, it always spawns at center of the screen.

**Comment by SleepingPanda** [comment]
I changed the position manually with dconf-tools and it seems to stick now. Maybe it's a wm issue? I'll close this for now. Thanks for taking the time to test and triage. Sorry for wasting your time.
