### ISSUE TITLE
Feature Request: Wingpanel Display Option

### ISSUE THREAD

**Issue by ergose** [lainsce/coin#13]
I just saw this in the ElementaryOS store and thought I'd check it out. Looks good, but I was hoping there would be a way to have the preferred currency shown on the Wingpanel at the top of the screen. I'd rather something like this to always be running there. 

I'm picturing this:
1) Right click on the window after setting the from and to currency.
2) Selecting 'Show on wingpanel' or similar.
3) Window goes away and (assuming to USD) something like 'ETH $206.07' appears on Wingpanel somewhere. To the right of 'Applications' would be nice for something like this, but top right would be cool too.

**Comment by lainsce** [comment]
I’ve read your request, but, unfortunately, for me to put anything on the panel, I’d need to make a Switchboard Plug(like Color), which is restricted to system apps. So, sadly I would have to turn down your request due to the complexity and restrictions. 😞
