### ISSUE TITLE
Add more currencies

### ISSUE THREAD

**Issue by drequivalent** [lainsce/coin#15]
This program needs either more currencies, or a way to add them.
The best way I think is, just load a list of currencies off of cryptocompare.com and let the user decide which ones they want to see.

**Comment by lainsce** [comment]
Which currencies do you want featured in Coin? 😄 

I need to boilerplate them due to how Vala works, there's no way of loading a list to form the combo-boxes.

**Comment by kmf** [comment]
ZAR would be cool

**Comment by lainsce** [comment]
@kmf What currency/cryptocurrency is ZAR, and what is it's symbol?

**Comment by kmf** [comment]
It's South African Rand and the Symbol is R

**Comment by lainsce** [comment]
Added in 1.1.5! Expect it when it releases!

**Comment by kmf** [comment]
Thanks
