### ISSUE TITLE
Indian Rupee

### ISSUE THREAD

**Issue by ar0ra1** [lainsce/coin#20]
First, it's Rupee and not Ruppee

Second, Apart from Bitcoin if I select any other coin, the amount doesn't show up. It remains ₹ 0.0

**Comment by lainsce** [comment]
Maybe the API stopped linking rupees with any cryptocurrency. I'll fix it when I can about the name.

**Comment by ar0ra1** [comment]
API is working fine 
https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=INR

**Comment by lainsce** [comment]
I see. Will see what's wrong in code when I can

**Comment by lainsce** [comment]
It's fixed in master, releasing in 1.2.1
