### ISSUE TITLE
Please look at replacing Bitcoin's symbol to its proper code point, U+20BF (₿)

### ISSUE THREAD

**Issue by fitojb** [lainsce/coin#21]
https://github.com/lainsce/coin/blob/76654d2747551e4ed17c0fb64d27419233a970ab/src/MainWindow.vala#L341

The most recent versions of most mainstream operating systems have implemented support for this Unicode 10.0 character in their system fonts (universal: Noto Sans, Windows: Arial/Times New Roman/Consolas/Cambria/Segoe UI/MS Sans Serif, macOS: SF UI).

**Comment by lainsce** [comment]
I'm using the current one because it's part of a better symbol for Bitcoin.
And also, it's better supported out of the box in elementary OS,
since it has the necessary fonts to display Ƀ, but not ₿ in the current version.
If Juno has the support for ₿, only then I will change it.

Read up more about it here: https://bitcoinsymbol.org/

**Comment by fitojb** [comment]
The page you cite is misleading and obsolete. It was a recommendation from before the actual symbol was encoded.

Reusing a letter as a currency symbol causes problems; there is a reason the Unicode standard categorizes its code points in accordance to their intended use; a character with the `Lu` (letter, uppercase) property will behave differently than one with the `Sc` property, causing potential parsing/layouting problems.

If you notice, I said “please look at replacing…”, implying that I am not expecting you to change the symbol right now. I know that font support takes time, but elementary is behind the times: it’ll be two years by now that other OSes have added the symbol.

**Comment by lainsce** [comment]
It's not on elementary's basket that you should throw a whine bomb at. It's Ubuntu's. If Ubuntu doesn't get the symbol because it didn't update the fonts packages in its repo, then I'm a sitting duck even with Juno.

**Comment by fitojb** [comment]
Ubuntu installs Symbola, which supports the symbol.

**Comment by lainsce** [comment]
I just have to see if Symbola is in the default Juno install then. :D

**Comment by lainsce** [comment]
Fixed in master, will be released in 1.2.1
