### ISSUE TITLE
Lingua PT-BR

### ISSUE THREAD

**Issue by LeandroStanger** [lainsce/coin#22]
Lingua PT-BR does not work

**Comment by lainsce** [comment]
I'll see what I can do and fix this.

**Comment by lainsce** [comment]
It's fixed in master, releasing in 1.2.1

**Comment by LeandroStanger** [comment]
# Did not work
![captura de tela de 2018-04-08 08-51-50](https://user-images.githubusercontent.com/26097419/38467113-4b198596-3b0a-11e8-83b7-208af574db14.png)

**Comment by lainsce** [comment]
Wait for FlatHub refresh if you're using the flatpak version.

**Comment by LeandroStanger** [comment]
## Lingua PT-BR does not work
![captura de tela de 2018-07-29 18-43-36](https://user-images.githubusercontent.com/26097419/43370984-5314994a-935f-11e8-8c34-7c6c31970d11.png)

**Comment by lainsce** [comment]
All I can say is wait for the Flatpak to have translations fixed.
If you compile from here, you'll get the translations.
