### ISSUE TITLE
Flatpak looks weird on ubuntu budgie

### ISSUE THREAD

**Issue by lf-araujo** [lainsce/coin#24]
Hi Lainsce,

Installing coin through flatpak goes without error, but the app is dissimilar to the picture in the readme:

![image](https://user-images.githubusercontent.com/10139950/38574939-832b254e-3cd0-11e8-93ee-dbac7519d665.png)

Thanks!

**Comment by lainsce** [comment]
That's because the README image is Coin in it's native habitat, elementary OS. There's nothing I can do to make it look ok in regards to window size, and to be honest, it doesn't detract from the usage of the app, does it?

**Comment by lf-araujo** [comment]
It works great. Thanks.
