### ISSUE TITLE
add Bitcoin Cash please

### ISSUE THREAD

**Issue by cocuba** [lainsce/coin#26]
Can you add Bitcoin Cash for currencies please?

**Comment by lainsce** [comment]
If it is in the API I use, I'll add it.

**Comment by lainsce** [comment]
It _is_ in the API, so expect an update shortly.

**Comment by eljefuri** [comment]
@lainsce Which API are you using? Why not support all tokens that are supported by the API?

**Comment by lainsce** [comment]
Because that would make a kilometric dropdown that would go all the way from Wingpanel to the Dock.
There's TOO MANY endpoints, so I just use those that people want.
