### ISSUE TITLE
Autorefresh stops working very soon

### ISSUE THREAD

**Issue by Octalus** [lainsce/coin#39]
Hey,

i really like your widget but after 1-2 refreshs after 10secs the autorefresh stops working.
After i change to another currency or another coin it checks the new price but not automatically in background.

I use an installation of elementaryOS 5 - which is basically an Ubuntu 18.04.2 LTS.

Would be nice to see this working.
Marcus

**Comment by lainsce** [comment]
I think the API got many checks in one session and auto-stopped working for refresh. Nothing I can do about that.
