### ISSUE TITLE
CombotBox Dark Theme

### ISSUE THREAD

**Issue by BellemareMederic** [lainsce/coin#41]
Hello there,

I put elementary OS in dark theme and the drop list for the current currency have problem with color. The text are dark green and the dark theme background for droplist are black :|

![Capture d'écran de 2019-12-28 11 51 17](https://user-images.githubusercontent.com/6710664/71546868-75540680-2968-11ea-8325-39d70a262708.png)

Linux PC 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lainsce** [comment]
Coin isn't optimized for the dark theme, I'm awaiting official dark theme support in elementary before changing anything.

**Comment by BellemareMederic** [comment]
Good 👍  happy new years !
