### ISSUE TITLE
Historical graph

### ISSUE THREAD

**Issue by ovari** [lainsce/coin#44]
Please enable showing a historical graph of the currency exchange rate
![Historical graph](https://user-images.githubusercontent.com/17465872/73586860-692f0c00-4507-11ea-809d-797d4c37208c.png)
https://fx-rate.net/HUF/BTC/#graph

What do you think?

Thanks

**Comment by lainsce** [comment]
I think that the API (backend) that I use doesn't do graphs via calls, I'd need to make the graph myself somehow and find a way to show it without cluttering the UI.
