### ISSUE TITLE
Bitcoin symbol shows as a box with the characters 20BF

### ISSUE THREAD

**Issue by ovari** [lainsce/coin#45]
* The Bitcoin symbol incorrectly shows as a box with the characters 20BF. The other virtual currencies are shown correctly.
* Flatpak version. Is there a way to get the version from the app?
* ![Bitcoin symbol](https://user-images.githubusercontent.com/17465872/73586907-333e5780-4508-11ea-8add-01744ea4be38.png)
* Linux Mint 19.3 Cinnamon 64-bit

Thanks

**Comment by lainsce** [comment]
I think that's caused by fonts in your system more than it being Flatpak. Try downloading Inter or Open Sans and the symbol will appear.
