### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by ruslankonev** [lainsce/coin#6]
![2017-06-23 00-37-35](https://user-images.githubusercontent.com/2588730/27457134-3d987450-57ac-11e7-994c-81568994fa11.png)

**Comment by lainsce** [comment]
Are you connected to the internet? 😃 
This app needs an internet connection to work.

**Comment by ruslankonev** [comment]
Of course. How I made this issue? =)

**Comment by lainsce** [comment]
Did the latest release fix it for you?
If not, maybe your internet provider blocks cryptocurrency sites.

**Comment by ruslankonev** [comment]
Yes, now work, thanks! Yet, it is possible to make currency switching by tabs?

**Comment by lainsce** [comment]
What do you mean by switching by tabs? 😃 

Also, please open a new issue for each of your bugs.
