### ISSUE TITLE
Move currencies to settings popover

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/coin#8]
Having a little settings cog in the top-right with a popover for the from/to currencies would get them out of the UI when they're likely only to be set once. That'd make the whole applet smaller and reduce the amount of chrome for something that's just meant to be looked at 99% of the time. :wink:

**Comment by lainsce** [comment]
I believe that this won't help the UX of Coin much, since users want to see the currencies and fiddle with them when they open the applet. I might however, move https://github.com/lainsce/coin/issues/9 to such a popover as a toggle "Auto-detect my Location".
